import { HorizontalBox, VerticalBox, LineEdit, Button } from "std-widgets.slint";
export component MainHeader inherits HorizontalBox {
    in-out property<string> version: "<not set>";
    in-out property<string> ip: "<not set>";
    callback refresh_ip;
    VerticalBox {
        Text {
            font-size: 20pt;
            font-weight: 600;
            text: "ASM: Ascended";
        }
        Text {
            vertical-alignment: bottom;
            text: "Version: \{version}";
        }
    }
    VerticalBox {
        Text {
            horizontal-alignment: center;
            text: "My Public IP";
        }
        HorizontalBox {
            LineEdit { 
                text: ip;
            }
            Button {
                icon: @image-url("../../res/icons/Refresh.ico");
                clicked => { refresh-ip() }
            }
        }
        Button {
            icon: @image-url("../../res/icons/Servers.ico");
            text: "Server Monitor";
        }
    }
    VerticalBox {
        Text {
            horizontal-alignment: center;
            text: "Task Status";
        }
        Text {
            text: "Auto-Backup: Unknown";
        }
        Text {
            text: "Auto-Update: Unknown";
        }
        Text {
            text: "Discord Bot: Disabled";
        }

    }

}