import { Button } from "std-widgets.slint";
import { ServerProfile } from "../models/server_profile.slint";
import { HorizontalBox } from "std-widgets.slint";

export component ProfileEdit inherits VerticalLayout {
    in-out property <ServerProfile> profile;
    callback save;
    callback close;
    HorizontalLayout {
        Text {
            vertical-alignment: top;
            horizontal-stretch: 1;
            font-size: 32px;
            text: "Profile: \{profile.id}";
        }
        Button {
            width: 100px;
            icon: @image-url("../../res/icons/Save.ico");
            clicked => { save() }
        }
        Button {
            width: 100px;
            icon: @image-url("../../res/icons/Cancel.ico");
            clicked => { close() }
        }
    }
    HorizontalLayout {
        vertical-stretch: 1;
    }
}