import { Button, VerticalBox , HorizontalBox, LineEdit, ListView , TabWidget} from "std-widgets.slint";
import { ServerProfile } from "../models/server_profile.slint";
import { ServerCard } from "server_card.slint";

export component ServersList inherits VerticalLayout {
    in-out property<[ServerProfile]> server_profiles;
    callback add_profile;
    callback remove_profiles;
    callback edit_profile(string);

    HorizontalLayout {
        height: 24px;
        Button {
            width: 44px;
            icon: @image-url("../../res/icons/Add.ico");
            clicked => { add_profile() }
        }
        Button {
            width: 44px;
            icon: @image-url("../../res/icons/Delete.ico");
            clicked => { remove_profiles() }
        }
    }
    ListView {
        width: 100%;
        height: 100%;
        for profile in server_profiles : ServerCard {
            profile: profile;
            edit_profile(id) => { edit_profile(id) }
        }
    }
}