import { ServerProfile } from "../models/server_profile.slint";
import { VerticalBox , HorizontalBox, Button} from "std-widgets.slint";

export component ServerCard {
    in-out property<ServerProfile> profile;
    callback edit_profile(string);
    Rectangle {
        border-color: darkgray;
        border-width: 1px;
        border-radius: 5px;
        VerticalBox { 
            HorizontalBox {
                padding: 0;
                Text {
                    vertical-alignment: center;
                    text: "Server: <unknown>";
                }
                Text {
                    vertical-alignment: center;
                    text: "Profile: \{profile.name}";
                }
                Button { 
                    width: 100px;
                    text: "Edit";
                    icon: @image-url("../../res/icons/Edit.ico");
                    clicked => { edit-profile(profile.id) }
                }
            }
            HorizontalBox {
                padding: 0;
                Text {
                    vertical-alignment: center;
                    text: "Install: \{profile.settings.installation_location}";
                }
                Text {
                    vertical-alignment: center;
                    text: "Version: \{profile.state.installed-version}";
                }
                Button { 
                    width: 100px;
                    text: "Install";
                    icon: @image-url("../../res/icons/Download.ico");
                    enabled: false;
                }
                Button {
                    width: 100px; 
                    text: "Start";
                    icon: @image-url("../../res/icons/Start.ico");
                    enabled: false;
                }
            }
        }
    }
}