import { VerticalBox , HorizontalBox, Button, TextEdit } from "std-widgets.slint";
import { GlobalConfiguration } from "../models/global_configuration.slint";

export component GlobalSettings inherits VerticalBox {
    callback open_steamcmd;
    callback update_steamcmd;
    callback set_steamcmd_location;

    callback open_profiles;
    callback set_profiles_location;

    HorizontalBox { 
        padding: 0;
        vertical-stretch: 0;
        height: 32px;
        Text {
            width: 75px;
            vertical-alignment: center;
            text: "SteamCMD:";
        }
        Text { 
            horizontal-alignment: left;
            vertical-alignment: center;
            horizontal-stretch: 1;
            text: GlobalConfiguration.steamcmd_directory;
        }
        Button  {
            width: 100px;
            text: "Open";
            icon: @image-url("../../res/icons/FolderOpen.ico");
            clicked => { open_steamcmd() }
        }
        Button  {
            width: 100px;
            text: "Update";
            icon: @image-url("../../res/icons/Refresh.ico");
            clicked => { update_steamcmd() }
        }
        Button  {
            width: 150px;
            text: "Set Location...";
            icon: @image-url("../../res/icons/FolderOpen.ico");
            clicked => { set_steamcmd_location() }
        }
    }
    HorizontalBox { 
        padding: 0;
        vertical-stretch: 0;
        height: 32px;
        Text {
            width: 75px;
            vertical-alignment: center;
            text: "Profiles:";
        }
        Text { 
            horizontal-alignment: left;
            vertical-alignment: center;
            horizontal-stretch: 1;
            text: GlobalConfiguration.profiles_directory;
        }
        Button  {
            width: 100px;
            text: "Open";
            icon: @image-url("../../res/icons/FolderOpen.ico");
            clicked => { open_profiles() }
        }
        Button  {
            width: 150px;
            text: "Set Location...";
            icon: @image-url("../../res/icons/FolderOpen.ico");
            enabled: false;
            clicked => { set_profiles_location() }
        }
    }
}