

import { Button, VerticalBox , HorizontalBox, LineEdit, ListView , TabWidget} from "std-widgets.slint";
import { MainHeader } from "components/mainheader.slint";
import { ProfileEdit } from "components/profile_edit.slint";
import { ServerProfile} from "models/server_profile.slint"; 
import { ServerState } from "models/server_state.slint";
import { ServersList } from "components/servers_list.slint";
import { GlobalSettings } from "windows/global_settings.slint";
import { GlobalConfiguration } from "models/global_configuration.slint";
import { ServersList } from "components/servers_list.slint";

export { GlobalConfiguration }

export enum MainState { Main, Edit }

export component AppWindow inherits Window {
    in-out property<[ServerProfile]> server_profiles;
    in-out property<ServerProfile> current_edit_profile;
    in-out property<MainState> state: MainState.Main;

    // Settings Callbacks
    callback set_steamcmd_location;
    callback set_profiles_location;
    callback open_steamcmd;
    callback update_steamcmd;
    callback open_profiles;

    // ServerList Callbacks
    callback add_profile;
    callback remove_profiles;
    callback edit_profile(string);

    // ProfileEdit Callbacks
    callback profile_edit_close;
    callback profile_edit_save;

    title: "ASM: Ascended (Version \{GlobalConfiguration.version})";
    min-width: 1024px;
    min-height: 768px;

    states [
        main when state == MainState.Main: {
            main_view.visible: true;
            profile_edit_view.visible: false;
        }
        edit when state == MainState.Edit: {
            main_view.visible: false;
            profile_edit_view.visible: true;
        }
    ]

    VerticalBox {
        MainHeader {
            vertical-stretch: 0;
            version: GlobalConfiguration.version;
            ip: GlobalConfiguration.local_ip;
        }
        GridLayout {
            vertical-stretch: 1;
            profile_edit_view := VerticalLayout {
                col :0;
                row :0;
                ProfileEdit {
                    profile: current-edit-profile;
                    close => { profile-edit-close() }
                    save => { profile-edit-save() }
                }
            }
            main_view := TabWidget { 
                col: 0;
                row: 0;
                Tab {
                    title: "Global Settings";
                    GlobalSettings {
                        set-steamcmd-location => { set-steamcmd-location() }
                        set-profiles-location => { set-profiles-location() }
                        open-steamcmd => { open-steamcmd() }
                        update-steamcmd => { update-steamcmd() }
                        open-profiles => { open-profiles() }
                    }   
                }
                Tab {
                    title: "Servers";
                    ServersList { 
                        server-profiles: server-profiles;
                        add-profile => { add-profile() }
                        remove-profiles => { remove-profiles() }
                        edit-profile(id) => { edit-profile(id) }
                    }
                }
            }
        }
    }
}
