

import { Button, VerticalBox , HorizontalBox, LineEdit, ListView , TabWidget} from "std-widgets.slint";
import { MainHeader } from "components/mainheader.slint";
import { ServerProfile} from "models/server_profile.slint"; 
import { ServerState } from "models/server_state.slint";
import { ServerCard } from "components/server_card.slint";
import { GlobalSettings } from "windows/global_settings.slint";
import { GlobalConfiguration } from "models/global_configuration.slint";

export { GlobalConfiguration }

export component AppWindow inherits Window {
    in-out property<[ServerProfile]> server_profiles;
    callback set_steamcmd_location;
    callback set_profiles_location;
    callback update_steamcmd;
    title: "ASM: Ascended (Version \{GlobalConfiguration.version})";
    width: 1024px;
    VerticalBox {
        MainHeader {
            version: GlobalConfiguration.version;
            ip: GlobalConfiguration.local_ip;
        }
        TabWidget { 
            Tab {
                title: "Global Settings";
                GlobalSettings {
                    set-steamcmd-location => { set-steamcmd-location() }
                    set-profiles-location => { set-profiles-location() }
                    update-steamcmd => { update-steamcmd() }
                }   
            }
            Tab {
                title: "Servers";
                ListView {
                    width: 100%;
                    height: 100%;
                    for profile in server_profiles : ServerCard {
                        profile: profile;
                    }
                    visible: false;
                }
            }
         } 
    }
}
