[package]
name = "package_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
structopt = "0.3.26"
serde = { version = "1.0.190", features = [ "derive"] }
serde_json = "1.0.108"
url = "2.5.0"
zip = "0.6.6"