[package]
name = "rcon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
err-derive = "0.3.1"
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.40"
